version: '3.8'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    user: root  # Run the container as root
    ports:
      - "9090:9090"  # Expose Prometheus on port 9090
    networks:
      - monitoring
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/var/lib/prometheus
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 500M

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_HTTP_PORT=3000
      - GF_SECURITY_ALLOW_EMBEDDING=true
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - monitoring
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 500M

  node_exporter:
    image: prom/node-exporter
    container_name: node_exporter
    ports:
      - "9100:9100"
    networks:
      - monitoring
    deploy:
      replicas: 1

  python-app-assignment:
    image: python-app-assignment:latest
    ports:
      - "8001:8000"
    environment:
      - PORT=8000
      - DOCKER_URL=tcp://172.27.36.125:2375
      - PROMETHEUS_HOST="0.0.0.0"
      - PROMETHEUS_PORT="5000"
    networks:
      - monitoring
    deploy:
      replicas: 1

networks:
  monitoring:
    driver: overlay  # Change from bridge to overlay network

volumes:
  grafana_data:
  prometheus_data:



# docker stack deploy -c docker-compose.yml my_thesis
