global:
  scrape_interval: 15s  # Default interval for scraping metrics

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']  # Address of your Alertmanager (or use AWS alerting)

rule_files:
  - "alert.rules.yml"  # Path to your alerting rules file (ensure you create alert.rules.yml)

scrape_configs:
  - job_name: 'docker'
    docker_sd_configs:
      - host: 'tcp://docker:2375'  # Use TCP connection to Docker

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']  # Scraping Prometheus itself

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']  # Node Exporter scraping

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']  # Grafana scraping

  - job_name: 'custom_app'
    static_configs:
      - targets: ['python-app-assignment:8000']

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"] 

  
    # metrics_path: '/metrics'
    # scheme: 'http'  # This is sufficient to indicate HTTP
